### ISSUE TITLE
FEATURE: Authorisation on server

### ISSUE THREAD

**Issue by codesnaper** [codesnaper/expense#26]
**Given** As a Developer
<br> **WHEN** any request come to server
</br>**THEN** it should be authorised with Amazon Cognito and should take claims and fetch the user id and append in the header for the controller. 

**Solution**
For all the requests, take the authorisation header and validate it through Cognito and should take claims and fetch the user id and append it in the header for the controller.

**Task**
- [x] Request should validate the token pass in the server.
- [x] #27
- [x] Enable Cross-origin on server. The request will come from the same origin.
- [x] User can sign up
- [x] #41
- [x] User can refresh token 
- [x] User can forget password
