### ISSUE TITLE
Bug API

### ISSUE THREAD

**Issue by codesnaper** [codesnaper/expense#42]
**Given** 
<br> **WHEN** API has been called
</br>**THEN** There are some bugs

**Solution**

**Task**
- [x] Tag should not able to delete if it is in use
- [x] Bank should have unique name wrt userid
- [x] Bank can be deleted for that user id for which API has been called.
- [x] Bank can be updated for that user id for which API has been called.
- [x] While Updating Bank, if Tag has been changed, changed in the tag mapping table.
- [x] While deleting Bank, tag mapping should delete the data.
- [x] Category should be deleted or updated by the user whose API has been called.
- [x] Category should be unique wrt the user id.
- [x] Account Should only be updated or deleted by the user for whom it was created.
- [x] Any Update or deletion in the account should also be done in the tag mapping table.
- [x] Tag can only be deleted by user who own it

**UI Design and Diagrams**
