### ISSUE TITLE
FEATURE

### ISSUE THREAD

**Issue by codesnaper** [codesnaper/expense#44]
**Given** 
<br> **WHEN** New Authentication implemented in Server
</br>**THEN** Authentication should work normally

**Solution**

**Task**
- [ ] Change in service of user
- [ ] Change in setting up profile
- [ ] Change in navigation drawer.
- [ ] Change in back service
- [ ] Change in account service
- [ ] Can create a new user
- [ ] can reset password

**UI Design and Diagrams**
