### ISSUE TITLE
FEATURE Expenditure

### ISSUE THREAD

**Issue by codesnaper** [codesnaper/expense#53]
**Given** 
<br> **WHEN** User add expenditure
</br>**THEN** API should be there to add

**Solution**
Expenditure Model: https://github.com/codesnaper/expense/blob/develop/expense-ui/src/modal/response/Expenditure.ts
Expenditure Entity:  https://github.com/codesnaper/expense/blob/main/expense-api/src/main/java/com/expense/expensemanagement/entity/Expenditure.java

At the time of adding the expenditure create an API post

**Task**
- [x] Check whether the limit has been exceeded. Yes Then exception is not to be added
- [x] If the limit is exceed the threshold then notify the user and add Expense.
- [x] If Expenditure Type is expense and account is normal account then deduct an amount in bank and account also.
- [x] If the expenditure type is income and the account is a normal account then add an amount in the bank and account also.
- [x] If the expenditure type is transfer and transfer of account is normal to normal, then deduct and add in the account table.
- [x] If the expenditure type is transfer and transfer of account is normal to the loan account, then deduct and deduct the amount in the loan table and deduct the amount in the bank table.

**UI Design and Diagrams**
NA
